Repository archlinuxmx/community-gateway, pull requests merged in 2021-03, with the labels that each got.

#16 Feature: Create Contributing Guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#27 feature: Create Ansible playbook to install required packages.
  .ansible-lint
  ansible/packages.yml
  ansible/templates/teleirc-env
  ansible/templates/teleirc.service
  ansible/user.yml
  packer/main.pkr.hcl
Labels: feature

#17 Feature: Create issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, enhancement

#15 Feature: Create Pull Request template
  .github/pull_request_template.md
Labels: documentation, enhancement

#29 feature: Add Ansible playbooks to harden the instance.
  .gitignore
  Makefile
  ansible/files/banner
  ansible/files/teleirc.service
  ansible/hardening.yml
  ansible/packages.yml
  ansible/requirements.yml
  ansible/templates/sshd_config.j2
  ansible/templates/teleirc-env.j2
  ansible/user.yml
  ansible/vars/ansible_sample.json
  packer/main.pkr.hcl
Labels: enhancement

#31 feature: Create TeleIRC env file using Jinja2 templates.
  ansible/packages.yml
  ansible/templates/teleirc-env.j2
  ansible/templates/teleirc.service.j2
  ansible/vars/ansible_sample.json
Labels: feature
